use crate::rules::{Finding, Severity};
use crate::scanner::ScanResult;

pub fn render(result: &ScanResult) -> String {
    let mut out = String::new();

    out.push_str("# agentwise Security Report\n\n");
    out.push_str(&format!(
        "**Score:** {}/100 ({})\n",
        result.score, result.grade
    ));
    out.push_str(&format!(
        "**Scanned:** {} {}, {} {}\n",
        result.configs_scanned,
        pluralize(result.configs_scanned, "config", "configs"),
        result.servers_scanned,
        pluralize(result.servers_scanned, "server", "servers")
    ));
    out.push_str(&format!(
        "**Duration:** {}\n\n",
        format_duration(result.duration_ms)
    ));

    out.push_str("## Summary\n\n");

    let critical = result
        .findings
        .iter()
        .filter(|f| f.severity == Severity::Critical)
        .count();
    let high = result
        .findings
        .iter()
        .filter(|f| f.severity == Severity::High)
        .count();
    let medium = result
        .findings
        .iter()
        .filter(|f| f.severity == Severity::Medium)
        .count();
    let low = result
        .findings
        .iter()
        .filter(|f| f.severity == Severity::Low)
        .count();
    let total = result.findings.len();

    out.push_str("| Severity | Count |\n");
    out.push_str("|----------|-------|\n");
    out.push_str(&format!(
        "| {} | {} |\n",
        escape_table_cell("Critical"),
        escape_table_cell(&critical.to_string())
    ));
    out.push_str(&format!(
        "| {} | {} |\n",
        escape_table_cell("High"),
        escape_table_cell(&high.to_string())
    ));
    out.push_str(&format!(
        "| {} | {} |\n",
        escape_table_cell("Medium"),
        escape_table_cell(&medium.to_string())
    ));
    out.push_str(&format!(
        "| {} | {} |\n",
        escape_table_cell("Low"),
        escape_table_cell(&low.to_string())
    ));
    out.push_str(&format!(
        "| **{}** | **{}** |\n\n",
        escape_table_cell("Total"),
        escape_table_cell(&total.to_string())
    ));

    out.push_str("## Findings\n\n");

    if result.findings.is_empty() {
        out.push_str("No security issues found.\n\n");
    } else {
        let mut findings = result.findings.clone();
        findings.sort_by(|a, b| {
            b.severity
                .cmp(&a.severity)
                .then_with(|| a.rule_id.cmp(&b.rule_id))
                .then_with(|| a.title.cmp(&b.title))
        });

        for finding in &findings {
            out.push_str(&render_finding(finding));
            out.push('\n');
        }
    }

    out.push_str("---\n");
    out.push_str(&format!(
        "*Generated by [agentwise](https://github.com/brandonwise/agentwise) v{}*\n",
        env!("CARGO_PKG_VERSION")
    ));

    out
}

fn render_finding(finding: &Finding) -> String {
    let icon = match finding.severity {
        Severity::Critical => "✖",
        Severity::High => "▲",
        Severity::Medium => "●",
        Severity::Low => "○",
    };

    let mut out = String::new();
    out.push_str(&format!(
        "### {} {}: {}\n",
        icon,
        finding.severity.as_str().to_uppercase(),
        finding.title
    ));
    out.push_str(&format!("- **Rule:** {}\n", finding.rule_id));
    out.push_str(&format!(
        "- **Config:** {} → {}\n",
        finding.config_file, finding.server_name
    ));

    if let Some(ref epss) = finding.epss {
        let probability = (epss.probability * 100.0).round() as i32;
        out.push_str(&format!(
            "- **EPSS:** {}% exploitation probability\n",
            probability
        ));
    }

    if let Some(ref items) = finding.sub_items {
        if !items.is_empty() {
            out.push_str("- **Supply Chain Signals:**\n");
            for item in items {
                out.push_str(&format!("  - {}\n", item));
            }
        }
    }

    out.push_str(&format!("- **Fix:** {}\n", finding.fix));
    out
}

fn escape_table_cell(value: &str) -> String {
    value.replace('|', "\\|")
}

fn pluralize<'a>(count: usize, singular: &'a str, plural: &'a str) -> &'a str {
    if count == 1 {
        singular
    } else {
        plural
    }
}

fn format_duration(duration_ms: u64) -> String {
    if duration_ms == 0 {
        "<1ms".to_string()
    } else {
        format!("{}ms", duration_ms)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_escape_table_cell_pipe() {
        assert_eq!(escape_table_cell("left|right"), "left\\|right");
    }

    #[test]
    fn test_markdown_empty_findings() {
        let result = crate::scanner::scan("testdata/empty-config.json");
        let output = render(&result);

        assert!(output.contains("No security issues found."));
        assert!(output.contains("| **Total** | **0** |"));
    }

    #[test]
    fn test_markdown_with_findings() {
        let result = crate::scanner::scan("testdata/vulnerable-mcp.json");
        let output = render(&result);

        assert!(output.contains("## Findings"));
        assert!(output.contains("### ✖ CRITICAL:"));
        assert!(output.contains("- **Rule:**"));
        assert!(output.contains("- **Fix:**"));
    }
}
